name: Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      working-directory: evaluation
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      working-directory: evaluation
      run: |
        python -m unittest discover -v

  lint:
    runs-on: ubuntu-latest
    name: Lintung (flake8)
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      working-directory: evaluation
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run flake8
      working-directory: evaluation
      run: |
        flake8 . --max-line-length=128

  type-check:
    runs-on: ubuntu-latest
    name: Type checking (mypy)
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      working-directory: evaluation
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run mypy
      working-directory: evaluation
      run: |
        mypy . --exclude ./env
